apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web
  namespace: dan
spec:
  project: default
  source:
    repoURL: https://git@github.com:dbastianelli/hackathon.git
    targetRevision: HEAD
    path: web
  destination:
    server: https://kubernetes.default.svc
    namespace: web
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
