apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: s1
  name: webapps1
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: mysql
  type: NodePort
status:
  loadBalancer: {}
